package io.github.thelastfrogrammer.elink;
import org.junit.Test;
import static org.junit.Assert.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class GcodeInspectorTest {
    private GcodeInspector.Report inspect(String text) throws Exception {
        File file = File.createTempFile("inspect-", ".gcode");
        try { try (OutputStream out = new FileOutputStream(file)) { out.write(text.getBytes(StandardCharsets.UTF_8)); } return GcodeInspector.inspect(file); }
        finally { file.delete(); }
    }
    @Test public void readsHeaderFooterEstimatesWithoutCountingCommentedCommands() throws Exception {
        GcodeInspector.Report r = inspect("; generated by ElegooSlicer test\r\n; total layer number = 200\n; T7\nG1 X1 ; T6\nN42 T0*17\n(T5)\nT2 ; change\n; machine_start_gcode = T4\\nT7\n; estimated printing time (normal mode) = 1h 20m\n; filament used [mm] = 0, 500\n");
        assertEquals(new TreeSet<>(Arrays.asList(0, 2)), r.tools);
        assertEquals("1h 20m", r.metadata.get("Slicer estimated time")); assertEquals("200", r.metadata.get("Reported layer count"));
        assertTrue(r.text().contains("not an exhaustive tool count")); assertTrue(r.text().contains("No tray mappings"));
    }
    @Test public void hashesExactBytesIncludingLineEndingsAndReadsFinalLine() throws Exception {
        GcodeInspector.Report r = inspect("abc"); assertEquals(1, r.lines); assertEquals(3, r.bytes);
        assertEquals("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad", r.sha256);
        assertNotEquals(r.sha256, inspect("abc\n").sha256);
        assertEquals(Collections.singleton(1), inspect("\uFEFFT1").tools);
    }
    @Test public void overlongLinesAreSkippedAndLaterSelectionsStillRead() throws Exception {
        char[] huge = new char[20000]; Arrays.fill(huge, 'A');
        GcodeInspector.Report r = inspect("T7 " + new String(huge) + "\nT1\n");
        assertTrue(r.longLines); assertEquals(Collections.singleton(1), r.tools);
    }
    @Test public void binaryContentInvalidatesAllTextInferences() throws Exception {
        GcodeInspector.Report r = inspect("; layer_count = 2\nT0\n\0binary");
        assertTrue(r.binary); assertTrue(r.tools.isEmpty()); assertTrue(r.metadata.isEmpty()); assertTrue(r.text().contains("unavailable"));
    }
    @Test public void unknownMacroSelectorsAndSpecialToolsAreNotReinterpretedAsTrayCount() throws Exception {
        GcodeInspector.Report r = inspect("T1000\nT255\nACTIVATE_EXTRUDER EXTRUDER=extruder\nT-1\nT0not-a-command\n");
        assertEquals(new TreeSet<>(Arrays.asList(255, 1000)), r.tools); assertTrue(r.text().contains("sentinel"));
    }
    @Test public void boundsMetadataAndKeepsConfiguredSemicolonSeparatedMaterials() throws Exception {
        char[] huge = new char[1000]; Arrays.fill(huge, 'a');
        GcodeInspector.Report r = inspect("; printer_model = " + new String(huge) + "\n; filament_type = PLA;PETG\n; irrelevant_secret = value\n");
        assertTrue(r.metadata.get("Configured printer model").length() <= 241); assertEquals("PLA;PETG", r.metadata.get("Configured filament types")); assertFalse(r.text().contains("irrelevant_secret"));
    }
    @Test public void interruptionAndEmptyFileFailWithoutPartialReport() throws Exception {
        Thread.currentThread().interrupt();
        try { inspect("T0"); fail(); } catch (InterruptedIOException expected) { } finally { Thread.interrupted(); }
        try { inspect(""); fail(); } catch (IOException expected) { }
    }
    @Test public void primaryColonHeaderAndImageDoNotContaminateToolOrMaterialEvidence() throws Exception {
        GcodeInspector.Report r=inspect("; total layer number: 100\n"+EmbeddedThumbnailTest.block("thumbnail",2,3,EmbeddedThumbnailTest.png(2,3))+"T0\n; filament used [mm] = 0,100\n; filament_type = PLA;PETG\n; filament_colour = #123456;#ABCDEF\n");
        assertEquals("100",r.metadata.get("Reported layer count"));assertNotNull(r.thumbnail);assertEquals(Collections.singleton(0),r.tools);assertEquals("PETG",r.materials.entries.get(1).type);assertEquals(Double.valueOf(100),r.materials.entries.get(1).lengthMm);assertFalse(r.text().contains("iVBOR"));
    }
    @Test public void binaryContentClearsEarlierPreviewAndMaterialEvidence() throws Exception {
        GcodeInspector.Report r=inspect(EmbeddedThumbnailTest.block("thumbnail",1,1,EmbeddedThumbnailTest.png(1,1))+"; filament_type = PLA\n\0binary");assertTrue(r.binary);assertNull(r.thumbnail);assertTrue(r.materials.entries.isEmpty());
    }
}
